wandb_version: 1

batch_size:
  value: 2048
d_layers:
  value: 512
data_path:
  value: ../../data/news
dataset:
  value: news
dim_t:
  value: 128
dropout:
  value: 0.5
log_interval:
  value: 50
lr:
  value: 0.01
n_layers:
  value: 4
num_epochs:
  value: 4000
seed:
  value: 42
task_type:
  value: regression
