entity: andresguzco
project: XVFM
name: default
program: ../../main.py
command:
    - ${env}
    - python
    - ${program}
    - ${args}
method: random
metric:
    goal: minimize
    name: loss
parameters:
    logging:
        value: 50
    dataset:
        value: "default"
    data_path:
        value: "../../data/default"
    task_type:
        value: "binclass"
    epochs:
        value: 8000
    batch_size:
        value: 1024
    lr:
        distribution: log_uniform_values
        min: 1e-5
        max: 1e-2
    loss:
        values: ['llk', 'classic']
