_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 103
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 256
dataset:
    value: mnist
int_method:
    value: euler
integration_steps:
    value: 100
learn_sigma:
    value: true
learned_structure:
    value: vector
log_interval:
    value: 100
loss_fn:
    value: Gaussian
lr:
    value: 0.001
num_epochs:
    value: 1000
save_model:
    value: false
sigma:
    value: 0.1
