wandb_version: 1

dataset:
  desc: null
  value: adult
data_path:
  desc: null
  value: data/adult
task_type:
  desc: null
  value: binclass
epochs:
  desc: null
  value: 8000
batch_size:
  desc: null
  value: 4096
lr:
  desc: null
  value: 0.001
logging:
  desc: null
  value: 100
loss:
  desc: null
  value: llk
num_eval:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.16.6
    framework: xgboost
    huggingface_version: 4.48.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739935569.0
    t:
      1:
      - 1
      - 4
      - 5
      - 6
      - 11
      - 35
      - 41
      - 48
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 4
      - 5
      - 6
      - 11
      - 35
      - 41
      - 48
      - 49
      - 53
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.11.11
      5: 0.16.6
      6: 4.48.1
      8:
      - 5
      13: linux-x86_64
