wandb_version: 1

batch_size:
  value: 2048
d_layers:
  value: 1024
data_path:
  value: ../../data/default
dataset:
  value: default
dim_t:
  value: 64
dropout:
  value: 0.3
log_interval:
  value: 50
lr:
  value: 0.01
n_layers:
  value: 4
num_epochs:
  value: 4000
seed:
  value: 42
task_type:
  value: binclass
