_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 55
                - 103
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 256
checkpoint_dir:
    value: checkpoints
checkpoint_interval:
    value: 50
dataset:
    value: two_moons
int_method:
    value: euler
integration_steps:
    value: 100
learn_sigma:
    value: false
learned_structure:
    value: scalar
log_interval:
    value: 100
loss_fn:
    value: Gaussian
lr:
    value: 0.001
num_epochs:
    value: 1000
results_dir:
    value: results
save_model:
    value: false
seed:
    value: 42
sigma:
    value: 0.1
