_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 4
                - 5
                - 6
                - 11
                - 35
                - 41
                - 48
                - 49
                - 53
                - 55
            "2":
                - 1
                - 4
                - 5
                - 6
                - 11
                - 35
                - 41
                - 48
                - 49
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.18.0
            "6": 4.50.0
            "8":
                - 5
            "12": 0.18.0
            "13": darwin-arm64
batch_size:
    value: 4096
data_path:
    value: data/adult
dataset:
    value: null
epochs:
    value: 8000
logging:
    value: 100
loss:
    value: llk
lr:
    value: 0.001
num_eval:
    value: 1000
task_type:
    value: null
