wandb_version: 1

batch_size:
  value: 1024
d_layers:
  value: 1024
data_path:
  value: ../../data/shoppers
dataset:
  value: shoppers
dim_t:
  value: 256
dropout:
  value: 0.1
log_interval:
  value: 50
lr:
  value: 0.01
n_layers:
  value: 5
num_epochs:
  value: 4000
seed:
  value: 42
task_type:
  value: binclass
